In [1]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

In [2]:
data = pd.read_csv("jester-data-1.csv", header=None)

In [3]:
n_features = 2

#user_ratings = data.values
user_ratings = data.values[0:100]
latent_user_preferences = np.random.random((user_ratings.shape[0], n_features))
latent_item_features = np.random.random((user_ratings.shape[1],n_features))

In [4]:
latent_item_features

array([[0.777, 0.806],
       [0.533, 0.79 ],
       [0.689, 0.244],
       [0.091, 0.895],
       [0.954, 0.966],
       [0.781, 0.669],
       [0.355, 0.364],
       [0.816, 0.207],
       [0.513, 0.405],
       [0.015, 0.919],
       [0.017, 0.818],
       [0.584, 0.876],
       [0.317, 0.493],
       [0.464, 0.162],
       [0.185, 0.591],
       [0.045, 0.68 ],
       [0.093, 0.858],
       [0.974, 0.518],
       [0.187, 0.75 ],
       [0.123, 0.033],
       [0.376, 0.052],
       [0.796, 0.766],
       [0.824, 0.368],
       [0.159, 0.136],
       [0.961, 0.287],
       [0.516, 0.723],
       [0.234, 0.657],
       [0.221, 0.411],
       [0.401, 0.587],
       [0.778, 0.752],
       [0.594, 0.565],
       [0.131, 0.466],
       [0.664, 0.622],
       [0.703, 0.699],
       [0.031, 0.927],
       [0.527, 0.949],
       [0.358, 0.863],
       [0.782, 0.1  ],
       [0.288, 0.102],
       [0.548, 0.071],
       [0.882, 0.172],
       [0.159, 0.385],
       [0.648, 0.587],
       [0.4

In [5]:
latent_user_preferences

array([[0.905, 0.719],
       [0.921, 0.196],
       [0.973, 0.113],
       [0.417, 0.607],
       [0.263, 0.459],
       [0.698, 0.123],
       [0.108, 0.094],
       [0.525, 0.502],
       [0.933, 0.524],
       [0.931, 0.281],
       [0.039, 0.94 ],
       [0.52 , 0.267],
       [0.484, 0.365],
       [0.017, 0.626],
       [0.33 , 0.27 ],
       [0.411, 0.058],
       [0.915, 0.099],
       [0.786, 0.838],
       [0.147, 0.928],
       [0.282, 0.518],
       [0.615, 0.157],
       [0.475, 0.165],
       [0.656, 0.714],
       [0.932, 0.489],
       [0.109, 0.757],
       [0.145, 0.55 ],
       [0.565, 0.999],
       [0.167, 0.164],
       [0.432, 0.297],
       [0.334, 0.187],
       [0.246, 0.907],
       [0.29 , 0.252],
       [0.097, 0.241],
       [0.588, 0.587],
       [0.606, 0.239],
       [0.625, 0.653],
       [0.378, 0.346],
       [0.611, 0.366],
       [0.678, 0.539],
       [0.924, 0.636],
       [0.801, 0.852],
       [0.196, 0.029],
       [0.241, 0.864],
       [0.8

In [6]:
def predict_rating(user_id,item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)

def train(user_id, item_id, rating,alpha = 0.0001):
    
    #print item_id
    prediction_rating = predict_rating(user_id, item_id)
    err =  ( prediction_rating- rating );
    #print err
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    


def sgd(iterations = 100000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(0,iterations):
        error = []
        for user_id in range(0,latent_user_preferences.shape[0]):
            for item_id in range(0,latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                if(not np.isnan(rating)):
                    err = train(user_id,item_id,rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if(iteration%10000 == 0 ):
            print (mse)

In [7]:
sgd()

2652.420511214622


KeyboardInterrupt: 

In [8]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[ 93.155,  10.637,  -7.095, ...,  88.805,  79.775,  84.314],
       [  2.019,   0.569,   0.129, ...,   2.217,   2.009,   2.159],
       [ 33.34 ,  72.08 ,  54.38 , ...,  90.687,  84.978,  97.042],
       ...,
       [ 28.335,  83.272,  64.568, ...,  96.064,  90.414, 104.033],
       [  5.508,  -2.281,  -2.845, ...,   2.741,   2.312,   2.136],
       [ 30.628,  75.437,  57.643, ...,  91.265,  85.686,  98.178]])

In [ ]:
values = [zip(user_ratings[i], predictions[i]) for i in range(0,predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = data.columns
comparison_data.applymap(lambda x: "(%2.3f|%2.3f)"%(x[0],x[1]))

0                1                2                 3    \
0    (74.000|93.155)  (-7.820|10.637)   (8.790|-7.095)   (-9.660|-0.956)   
1    (100.000|2.019)    (4.080|0.569)   (-0.290|0.129)     (6.360|0.474)   
2    (49.000|33.340)  (99.000|72.080)  (99.000|54.380)   (99.000|99.333)   
3    (48.000|28.377)  (99.000|75.835)   (8.350|58.360)  (99.000|105.692)   
4    (91.000|15.878)   (8.500|-1.595)   (4.610|-4.050)   (-4.170|-5.138)   
5    (100.000|3.763)  (-6.170|-7.758)  (-3.540|-7.113)   (0.440|-11.993)   
6    (47.000|30.097)  (99.000|75.561)  (99.000|57.837)  (99.000|104.988)   
7    (100.000|4.365)   (6.840|-5.433)   (3.160|-5.278)    (9.170|-8.705)   
8    (100.000|4.176)  (-3.790|-4.089)  (-3.540|-4.124)   (-9.420|-6.708)   
9    (72.000|91.989)   (3.010|21.096)    (5.150|1.824)    (5.150|14.521)   
10   (36.000|29.258)  (-2.910|81.267)   (4.080|62.738)  (99.000|113.467)   
11   (100.000|6.764)   (1.310|-3.261)   (1.800|-3.878)    (2.570|-5.958)   
12   (47.000|44.873)  (99.000|66.790)  (99.000|47.993)   (99.000|89.569)   
13   (100.000|3.547)    (9.220|1.437)    (9.270|0.590)     (9.220|1.470)   
14   (100.000|3.535)   (8.790|-3.729)  (-5.780|-3.715)    (6.020|-6.070)   
15   (100.000|4.957)  (-3.500|-3.674)   (1.550|-3.912)    (2.330|-6.241)   
16   (51.000|50.489)  (99.000|64.265)  (-9.270|44.925)   (99.000|84.888)   
17   (100.000|4.494)    (3.160|0.986)    (7.620|0.052)     (3.790|0.644)   
18   (49.000|31.226)   (4.220|70.125)   (3.640|53.111)   (99.000|96.852)   
19   (53.000|63.725)  (99.000|53.815)   (7.620|33.945)   (99.000|67.289)   
20   (55.000|48.923)   (2.570|53.641)  (-0.730|36.336)   (99.000|69.655)   
21   (50.000|23.392)   (7.280|68.863)   (5.390|53.402)   (99.000|96.396)   
22   (72.000|90.330)   (2.720|16.981)   (4.170|-1.322)     (6.500|8.806)   
23  (100.000|10.077)   (2.090|-3.839)  (-7.570|-4.927)    (4.170|-7.387)   
24   (74.000|68.604)   (-3.930|9.658)  (-1.170|-3.704)     (2.280|1.960)   
25   (67.000|91.767)  (99.000|27.449)    (5.490|7.159)    (3.450|23.834)   
26   (60.000|71.106)  (99.000|41.866)   (5.830|22.718)   (99.000|48.538)   
27   (72.000|96.942)   (0.490|14.057)   (0.150|-4.893)     (0.150|3.367)   
28   (54.000|55.019)  (99.000|57.704)  (99.000|38.680)   (99.000|74.509)   
29   (46.000|46.553)  (99.000|69.175)   (4.080|49.694)   (99.000|92.754)   
..               ...              ...              ...               ...   
70   (100.000|6.546)   (3.500|-3.033)   (6.210|-3.651)   (-0.630|-5.587)   
71   (68.000|92.131)  (-6.210|22.850)   (-0.100|3.262)   (-5.290|17.056)   
72   (100.000|2.182)   (5.440|-5.782)  (-2.670|-5.194)   (-7.960|-8.827)   
73   (67.000|71.789)   (9.270|34.921)   (9.170|16.812)    (9.270|38.279)   
74   (100.000|8.258)   (2.380|-3.436)  (-5.440|-4.280)   (-8.110|-6.477)   
75   (48.000|43.826)  (99.000|68.659)  (99.000|49.730)   (99.000|92.482)   
76   (100.000|6.825)  (-8.500|-2.180)  (-6.600|-2.987)   (-8.450|-4.390)   
77   (55.000|37.648)  (99.000|62.234)  (99.000|45.433)   (99.000|84.196)   
78   (100.000|4.605)   (2.280|-0.762)   (1.700|-1.424)   (-5.530|-1.927)   
79   (53.000|55.238)  (99.000|56.743)  (99.000|37.840)   (99.000|73.066)   
80   (38.000|27.568)  (99.000|74.369)  (99.000|57.277)  (99.000|103.696)   
81   (53.000|44.031)   (3.450|62.348)   (6.070|44.434)   (-9.270|83.232)   
82   (100.000|7.857)   (3.060|-5.644)   (6.500|-6.052)   (-7.910|-9.630)   
83   (72.000|89.947)  (-7.670|18.805)   (-6.990|0.264)   (-1.410|11.538)   
84   (41.000|26.819)  (99.000|81.780)  (99.000|63.584)  (99.000|114.648)   
85   (72.000|94.599)  (-1.500|17.617)   (3.300|-1.524)     (3.350|8.979)   
86   (100.000|5.931)    (2.820|1.431)    (5.440|0.177)     (7.570|1.040)   
87   (74.000|92.361)   (6.890|14.660)  (-9.660|-3.605)     (0.150|5.059)   
88  (72.000|101.107)  (-6.070|15.862)  (-5.580|-4.102)    (-6.170|5.265)   
89   (100.000|5.627)   (-0.920|0.241)   (1.650|-0.763)    (1.020|-0.644)   
90   (68.000|81.751)  (-3.160|26.720)   (-1.120|8.267)    (1.310|

In [ ]:
comparison_data

In [ ]:
comparison = comparison_data.to_latex()
text_file = open("comparison.txt", "w")
text_file.write(comparison)
text_file.close()